package com.automation.demo;

public class BillingAndInvoicing {
    // YOU ARE A BILLING COMPANY, YOU GENERATE BILLS AND INVOICES
    // YOU GET CLIENTS LIST AS INPUT
    // YOU GET CLIENTS TRANSACTIONS AS INPUT - THERE CAN BE MORE THAN ONE TRANSACTION FOR EACH CLIENT
    // CALCULATE THE FINAL BILL WITH BELOW CONDITIONS
    // IF 2% of TOTAL BILL FOR A CLIENT > $500 - DISCOUNT 5%
    // IF 2% of TOTAL BILL FOR A CLIENT > $750 - DISCOUNT 6%
    // IF 2% of TOTAL BILL FOR A CLIENT > $1000 - DISCOUNT 8%
    // DISPLAY FINAL BILL

}
